### ISSUE TITLE
Broken documentation

### ISSUE THREAD

**Issue by PhillipMwaniki** [chrisnharvey/magicLAMP#39]
**Describe the bug**
The documentation page https://magiclamp.app/automatic-dns is broken
<img width="1122" alt="image" src="https://user-images.githubusercontent.com/2037708/99365028-cbef6980-28c7-11eb-9cb1-f0328355a763.png">

**To Reproduce**
1. Head over to browser and paste this https://magiclamp.app/automatic-dns

**Expected behavior**
A well styled page

**Desktop (please complete the following information):**
 - MacOS Catalina 10.15.7
 - Firefox browser 82.0.3

**Comment by chrisnharvey** [comment]
@PhillipMwaniki That's strange. Looks like the version is missing from the URL. I will get this fixed.

In the meantime, you can access this page here: https://magiclamp.app/en/stable/automatic-dns/

**Comment by chrisnharvey** [comment]
@PhillipMwaniki This has been fixed in v1.4.1.
